"""penambahan 2 kolom

Revision ID: e6263c9ec3fe
Revises: ca7f9676c04c
Create Date: 2025-10-21 19:52:43.635313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6263c9ec3fe'
down_revision: Union[str, Sequence[str], None] = 'ca7f9676c04c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('tipe', sa.String(length=50), nullable=True))
    op.add_column('items', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'status')
    op.drop_column('items', 'tipe')
    # ### end Alembic commands ###
